#!/bin/bash

weeks=0

while IFS= read -r line; do
    if [[ $line =~ \(*([0-9]+)\ week[s]*\)* ]]; then
        echo "$line"
        # echo "${BASH_REMATCH[0]}"
        (( weeks += BASH_REMATCH[1] ))
    fi
done
echo "Total: $weeks"
