#!/bin/bash
# We can sum numbers in bash script by pass files or variables
# from command line like this:
# printf "first (23 days)\nanother (10 days)\n" | ./count
# or pass a file name to script

days=0
while IFS= read -r line; do
    if [[ $line =~ \(*([0-9]+)\ day[s]*\)* ]]; then
        echo "$line"
        # echo "${BASH_REMATCH[0]}"
        (( days += BASH_REMATCH[1] ))
    fi
done
echo "Total: $days"
